### ISSUE TITLE
[massiv-io] Automatic computation strategy detection

### ISSUE THREAD

**Issue by fosskers** [lehins/massiv#11]
I discovered experimentally that `readImage` will always produce an `Array` whose `Comp` is `Seq`. 

Not-unreasonably-expected-behaviour could be:

- Image reading itself is done in serial, regardless of CPU core count
- If `getNumCapabilities` is greater than 1 and/or the `Array` dimensions are high enough
  to make `Par` overhead worth it:
  - `ColorSpace` / cell type conversion (if necessary) could be in `Par`
  - The final `Array S` could be automatically set to `Par`

Questions:
- If `getNumCapabilities` is greater than 1, should everything be `Par`? Sure there might be a bit of unneeded overhead if the image is too small, but that might not be a typical use case. For GIS, we expect 256x256 rasters at minimum, with 512x512 and 1024x1024 also being typical. Giant ones like 65k x 65k are also out there, and are a use-case I'd like to support in `mapalgebra`.

**Comment by lehins** [comment]
On very small images overhead is negligible, moreover it is rather unusual case, since larger images (on the order of at least 100s of pixels) are more common. For that reason the default computation strategy was switched to `Par` and can be changed with `setCom Seq` at anytime if necessary on the decoded `Image`.
