### ISSUE TITLE
massiv-serialise/persist testsuites need lot of mem to build

### ISSUE THREAD

**Issue by juhp** [lehins/massiv#117]
While building the next Stackage Nightly snapshot,
I ran into massiv-serialise and massiv-persist using roughly
~50% and %40 of the build server memory respectively (based on `ps` output).
This may be expected but I just wanted to ask if you have
any idea of whether the tests memory usage changed recently.

For now I reduced our build to -j1 so that they don't build in parallel.

**Comment by juhp** [comment]
Actually with -j1 stackage building, massiv-serialise is now using 90% of ram to build `tests/Main.hs`.

**Comment by lehins** [comment]
Thank you for pointing this out. I've split out test suites for both packages into smaller modules, which reduces ghc memory bloat significantly during building. This problem was caused by a module with lots of functions that rely on inlining. I've seen such problem before in vector's test suite (haskell/vector#274) If problem persists then turning off optimizations with `--fast` will completely alleviate the problem.

I've released new versions for both packages that should no longer exhibit this problem to such extent, but feel free to reopen this ticket if you still observe unreasonably excessive memory usage from ghc.

**Comment by juhp** [comment]
Thank you!

Btw great talk at HaskellX!
