### ISSUE TITLE
[question] Escape from DW

### ISSUE THREAD

**Issue by fosskers** [lehins/massiv#16]
This is half a question and half me trying to work out where one can go after getting an `Array DW`.

So, `DW` doesn't have a `Source` instance, meaning we can't `zipWith` two `Array DW`. This makes doing Local Operations (binary ops on two Rasters) harder with two `Array DW` (the output of a *Focal* op), since you'd have to force the memory once to get something `Source`, then continue.

We can't `writeImage` on an `Array DW` for the same reason, but that makes sense to me. `computeAs S` beforehand makes a lot of sense.

We can't `delay` an `Array DW` either (as we discussed before), but this also makes sense.
You'd lose all the goodness that `DW` provides.

We *can* `displayImage` an `Array DW`. How does this work? Is the Array silently forced to some concrete Representation before being fed to the image viewer?

Am I missing anything? Where else can an `Array DW` go? By constrast, it seems like `Array D` can go just about anywhere.

**Comment by fosskers** [comment]
Crap, no, `displayImage` transitively requires `Source` too.

**Comment by lehins** [comment]
You bring up some good points. Let's see.
It's true, `DW` doesn't have many instances, but there are some things that can be done to it without hurting the performance. `Array DW ix` is an instance of `Functor`, so we can `fmap` stuff over it. We can also `resize` and `extract` from it, since it has an instance of `Size`. Well and the last thing, naturally, we can `Load` it into some manifest representation, i.e. `compute` it.

As far as `zipWith`, that's better done over `Stencil`s, since it has instance for  `Applicative`, rather than `DW` arrays.

Now as far as `writeImage` and `displayImage` go, I don't see any reason why we can't have an instance of `Writeable` for `DW` arrays, so that will be a good and easy feature to add, I think.

**Comment by fosskers** [comment]
I have a function `grayscale` that one can use to easily prepare a `Raster` for quick demo viewing:
```haskell
-- | Convert a `Raster` into a 'massiv-io' `Image` for easy output with functions
-- like `writeImage`.
grayscale :: Functor (Raster u p r c) => Raster u p r c a -> Raster u p r c (Pixel Y a)
grayscale = fmap PixelY
{-# INLINE grayscale #-}
```
and I'm trying to get this to compile, but the missing `Source` instance for `DW` kills it:
```haskell
-- | View a `Raster` as grayscale with the default image viewer of your OS.
--
-- For more direct control, consider `displayImage` from 'massiv-io'.
display :: (Functor (Raster u p r c), Elevator a) => Raster u p r c a -> IO ()
display = displayImage . _array . grayscale
```

**Comment by lehins** [comment]
Just do: `display = displayImage . computeAs S . _array . grayscale`

**Comment by fosskers** [comment]
Yeah, true. Then "buyer beware" if they're trying to demo some massive thing that won't fit in memory.

**Comment by lehins** [comment]
Unfortunately, it's true, you can't display an image if you can't fit into memory :)

**Comment by fosskers** [comment]
Nice! That helps close the gap for demoing focal ops.

As you mentioned, `DW` let's us `fmap`, so we can still do unary local ops after a focal op.
The dream is still to be able to do more binary local ops after a focal. Most of my local ops are currently constrained by the input Rasters having a `Source` instance.

**Comment by lehins** [comment]
To sum it up: Computation of `DW` arrays is highly optimized, as such those array types are limited in functionality.

On the other hand, this issue did bring to my attention an extra feature that could be added, which will be tracked by a separate ticket #18
