### ISSUE TITLE
`zipWith (+)` vs `(.+)` 

### ISSUE THREAD

**Issue by fosskers** [lehins/massiv#23]
From an email exchange we had:

> Hey Alexey, I was doing a bit of benchmarking this morning and noticed that `zipWith (+)` and friends are about twice as fast as their counterparts in `Data.Massiv.Array.Numeric`(like `(.+)`). Looking at the code, I see those operators using `liftArray2`, while `zipWith` does its own work.

<hr>

> Great find, and also an unfortunate one. `zipWith (+)` and `liftArray2 (+)` are almost identical except the latter errors out on mismatched size and looks at two extra cases when either one of the arguments is an array with one element. Those two extra case causes ghc failing to properly apply some optimizations, thus causing a significant slowdown (it's even more drastic in my benchmark, a factor of 4) 
> Good thing for all of the binary operators like `(.+)`, `(.*)`, is that those case that cause the slowdown aren't that important, but using `zipWith (+)` would not be correct, since it will silently discard elements on mismatched size arrays (it doesn't affect mapalgebra, since you check size equality at the type level).

**Comment by lehins** [comment]
Doing a bunch of experiments it looks like the only way to get the performance to match the `zipWith (+)` is to use it as implementation. This will have minimal impact on `(.+)` and related, namely it will be impossible to use them with scalar values, eg. `range Seq 0 10 .+ singleton 5`, which doesn't seem to be terribly important, IMHO.

I am still considering using a bit slower implementation for `Num` instance, since it does bring some convenience to the table, namely using numeric literals as arrays: eg. `range Seq 0 10 + 5`.

In any case, this change will come into effect in `massiv-0.3.0`, since that is a breaking change.
