### ISSUE TITLE
Bad performance with delayed values

### ISSUE THREAD

**Issue by mkawalec** [lehins/massiv#38]
I've built a simple raytracer with `massiv` and noticed it had an abysmal performance. I've created it using delayed arrays all the way, apart from the top level when they are computed to get the result. After some investigation I found that code
```
a = dot direction direction
b = dot oc direction
```
computes `direction` and all of it's computation subtree three times, even though all the arrays involved are delayed. 

This is most likely just an issue with my mental model of how delayed should work in that scenario (ie. compute `direction` once and stick it in all the places), but I think it should be more visible in the docs that delayed should effectively never be used apart from the cases where values are indeed coming from a generator function. If it's not an issue with my mental model and is indeed a bug, I am happy to provide the repro code ;)

**Comment by lehins** [comment]
@mkawalec It is a common pitfall of delayed arrays, if used improperly it can hurt performance really bad. Documentation certainly should be improved with especial emphasis on examples.

Considering your case of simple ray tracer, I would really love to see the actual code and would be happy to give you suggestions on how performance can be improved. Other reasons I'd love to see it cause: 

* I always wanted to write a ray tracer myself, but never gotten around on doing that
* So I can see, maybe there is an actual problem with `massiv` implementation.
* If the performance issue is indeed due to your mental model, I'd like to understand it and see if there is a way I can prevent it from happening. 

The pitfall with delayed arrays you are talking about in this issue is a very common one as well and that's why I explicitly talked about during Monadic Warsaw ;)

In the example below every element in array `a` will be evaluated twice, once `b` is computed:

```haskell
let a = makeArrayR D Seq (Ix1 10) (^ (10 :: Int))
let b = A.zipWith (+) a a
```

**Comment by mkawalec** [comment]
Exactly! My mental model was that I can operate cheaply and easily on delayed values and make them non-delayed at the very end. The fact that only `D` is a member of `num` reinforced that assumption :stuck_out_tongue: 

Here's the code https://github.com/mkawalec/raytracer, I'm effectively porting https://www.amazon.com/Ray-Tracing-Weekend-Minibooks-Book-ebook/dp/B01B5AODD8 to Haskell. Tomorrow I'm going to replace `D` with `P` everywhere and see where this gets me.

**Comment by mkawalec** [comment]
Now it's a rough cut with `P` and it finally became linear in complexity depending on the number of bounces, not exponential. I'm going to make the code nicer and optimize further.

**Comment by mkawalec** [comment]
Everything works as intended if I use delayed values as expected
