### ISSUE TITLE
Monadic maps that keep the result

### ISSUE THREAD

**Issue by cocreature** [lehins/massiv#5]
Currently the `massiv` API seems to be lacking monadic map operations, in particular `mapM` and `imapM`. These operations are tricky to implement since they can’t be delayed so I guess they might be intentionally omitted? Since these operations are quite common in Haskell, I think it makes sense to either implement them in `massiv` and maybe add a warning that they will create a new array and can thereby be expensive or add a comment to the docs explaining why these operations are not provided. I don’t have a particularly strong preference regarding the two options.

Keep up the good work, I really like the lib so far!

**Comment by lehins** [comment]
@cocreature Thank you for the suggestion and the complements.

You were right on point, `mapM`, `imapM` a very useful and extremely popular abstractions in Haskell, and they were indeed left out for a reason. Not only that resulting array cannot be delayed stands in the way, but also the fact that a satisfactory implementation isn't trivial, and the trivial implementation is not satisfactory. So I decided to leave off the addition of those functions to the better times. I will keep this ticket opened until then, as I do want to have those functions implemented in the near future.

**Comment by cocreature** [comment]
Slightly related to this, I also just saw that there is no monadic version of `makeArray`. There is `unsafeGenerateM` but that’s part of `Ragged` which afaict only has an instance for lists. Compared to `mapM` and `imapM` this seems relatively straightforward to add for the materialized representations but it could very well be the case that I’m missing something.

**Comment by lehins** [comment]
You are again right on point :) It is not slightly, but directly related to this issue. If there was `makeArrayM`, this problem would be solved. But implementing `makeArrayM` that is the hard part.

Here is the trivial solution I mentioned before:

```haskell
imapListM
  :: (Ragged L ix e', Monad m, Size r ix e) =>
     (ix -> m e') -> Array r ix e -> m (Array L ix e')
imapListM f arr = unsafeGenerateM (getComp arr) (size arr) f

imapM :: (Size r ix e, Ragged L ix e', Mutable r' ix e', Monad m) =>
         (ix -> m e') -> Array r ix e -> m (Array r' ix e')
imapM f = fmap fromRaggedArray' . imapListM f
```

Here we need to piggy pack on lists in order to get `mapM` working, which I am not really in favor of, there is gotta be a better way out there.

**Comment by lehins** [comment]
Now, once I figure out instances for true Ragged arrays, that's when I think the solution will fall right into place.

**Comment by cocreature** [comment]
Sounds good, thanks for the quick responses!

**Comment by lehins** [comment]
It turns out that above implementation isn't as bad as I thought. Benchmarking `mapM` against `vector` library (that also falls back onto lists AFAIK), yields only a slightly slower version, and that is taking into account that vector operates on a flat list/vector, where massiv preserves structure using nested lists. Moreover I was able to figure out a parallel version of `unsafeGenerateM` for lists, which makes it possible to parallelize monadic construction of nested lists:

```
benchmarking mapM/Vector U
time                 244.1 ms   (186.5 ms .. 288.8 ms)
                     0.983 R²   (0.938 R² .. 1.000 R²)
mean                 284.4 ms   (263.1 ms .. 319.8 ms)
std dev              33.81 ms   (3.298 ms .. 42.57 ms)
variance introduced by outliers: 36% (moderately inflated)

benchmarking mapM/Array Ix2 U Seq
time                 383.6 ms   (312.8 ms .. 492.9 ms)
                     0.991 R²   (0.976 R² .. 1.000 R²)
mean                 388.7 ms   (369.0 ms .. 399.0 ms)
std dev              17.12 ms   (69.39 as .. 17.89 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking mapM/Array Ix2 U Par
time                 209.3 ms   (142.9 ms .. 259.2 ms)
                     0.957 R²   (0.790 R² .. 1.000 R²)
mean                 234.4 ms   (219.1 ms .. 264.3 ms)
std dev              31.30 ms   (2.563 ms .. 40.50 ms)
variance introduced by outliers: 32% (moderately inflated)
```

I still think it's not great to use lists for that purpose, but it is better than nothing, so, I think I'll include implementation for `mapM` and `imapM` I have now in the next release. We can optimize and make it faster in the future.

**Comment by cocreature** [comment]
Sounds great, thanks again for looking into this!

**Comment by lehins** [comment]
So, this issue was way to intriguing for me to just let it sit here. I figured out a way how to combine arbitrary monadic computation with creating arrays using mutation. It is a somewhat unusual approach, so I am still not 100% sure it is a safe way to do it, but it works and it works fast:

```
benchmarking mapM/Array Ix2 P Seq
time                 2.408 ms   (2.346 ms .. 2.464 ms)
                     0.994 R²   (0.991 R² .. 0.997 R²)
mean                 2.464 ms   (2.417 ms .. 2.532 ms)
std dev              183.6 μs   (135.2 μs .. 236.3 μs)
variance introduced by outliers: 53% (severely inflated)

benchmarking mapM/Array Ix2 U Seq
time                 5.858 ms   (5.508 ms .. 6.148 ms)
                     0.979 R²   (0.961 R² .. 0.989 R²)
mean                 5.627 ms   (5.476 ms .. 5.812 ms)
std dev              476.9 μs   (383.0 μs .. 621.8 μs)
variance introduced by outliers: 52% (severely inflated)

benchmarking mapM/Vector U
time                 269.6 ms   (216.1 ms .. 317.4 ms)
                     0.989 R²   (0.973 R² .. 1.000 R²)
mean                 272.2 ms   (261.7 ms .. 281.6 ms)
std dev              11.88 ms   (5.525 ms .. 15.30 ms)
variance introduced by outliers: 16% (moderately inflated)
```

I did add some tests, and played around with `mapM`/`generateM` a bit, so they seem to work great, but I still added them as an experimental feature for now, and placed them in `Data.Massiv.Array.Mutable`
I would really like to see some real uses of those functions and especially see them work properly in multi-threaded setting (i.e. used with `STM` monad for instance), before I declare those as reliable.
