### ISSUE TITLE
Taking a 1D slice of a 3D array

### ISSUE THREAD

**Issue by kozross** [lehins/massiv#55]
As I understand it, all the slicing functions produce slices of a 'dimensionality' exactly one lower than that of their first argument: for example, if I slice a 3D array, I will end up with a 2D array. If I want to slice 'lower' than this, does this mean I have to slice twice, or is there some other function that can do that slicing that I'm missing?

**Comment by lehins** [comment]
Yes, you are correct. All slicing functions lower dimension by one. Normally it be fine just to chain them, since all they do is just index manipulations and no intermediate arrays is created, but there are alternative ways to go about it. Consider this array and what we want is just this 1D slice `[3,4,5]`:

```haskell
λ> a = makeArrayR U Seq (2 :> 1 :. 3) (toLinearIndex (2 :> 1 :. 3))
λ> a
(Array U Seq (2 :> 1 :. 3)
  [ [ [ 0,1,2 ]
    ]
  , [ [ 3,4,5 ]
    ]
  ])
```
I'll use safe function for extracting ROI, which work on `Maybe a`, but it can just as well be done with with alternatives that throw errors instead. I can just slice it down to the region I want:

```haskell
λ> a !?> 1 ??> 0
Just (Array M Seq (3)
  [ 3,4,5 ])
λ> a !> 1 !> 0
(Array M Seq (3)
  [ 3,4,5 ])
```
The first slice already produces the vector we need, except that it is in a 2D form. To fix that we can simply resize it:
```haskell
λ> a !?> 1 >>= resize (Ix1 3)
Just (Array M Seq (3)
  [ 3,4,5 ])
```
Similarly it is possibly to acquire an arbitrary ROI with `extract` and `extractFromTo`, followed by a resize:
```haskell
λ> extract (1 :> 0 :. 0) (1 :> 1 :. 3) a >>= resize (Ix1 3)
Just (Array M Seq (3)
  [ 3,4,5 ])
```

Feel free to close this issue, if that answers you question. If you have some more ideas on how to easier achieve 3D to 1D slicing, I am all ears. ;)

**Comment by kozross** [comment]
Thanks, that answers my question. I don't really have any ideas on this - I asked this more to check my understanding if anything.
