### ISSUE TITLE
``zipInner``

### ISSUE THREAD

**Issue by kozross** [lehins/massiv#60]
The goal is to zip together an array of a dimensionality one smaller (but matching) and another array, by essentially zipping along the inner dimensions only. At the moment, I can write what I want by doing something like

```haskell
zipInner :: (Manifest r (Lower ix) a, Manifest r' ix b) => Array r (Lower ix) a -> Array r' ix b -> Array D ix (a,b)
zipInner a1 a2 = makeArray (getComp a1) (size a2) go
    where go i = (index' a1 (tailDim i), index' a2 i)
```
However, this requires me to have a ``Manifest`` constraint for both 'input' arrays, while ``zip`` and friends require only ``Source``. Is it possible to provide a function similar to this one, but with a signature like

```haskell
zipInner :: (Source r (Lower ix) a, Source r' ix b) => Array r (Lower ix) a -> Array r' ix b -> Array D ix (a,b)
```

This extends to other similar functions, like ``zip3``, ``zipWith``, and so forth.

**Comment by lehins** [comment]
Thanks for this question, it actually resulted in me finding and fixing a bug in `massiv`, so make sure to upgrade to the newest version `0.2.4.1`, which will be on hackage in a couple of hours once CI has passed.

To answer your question though, you are talking about a regular zip, right?
```haskell
λ> a2 = makeArrayR D Seq (2 :. 3) (toLinearIndex (2 :. 3))
λ> a2
(Array D Seq (2 :. 3)
  [ [ 0,1,2 ]
  , [ 3,4,5 ]
  ])
λ> a1 = makeArrayR D Seq (Ix1 3) (*10)
λ> a1
(Array D Seq (3)
  [ 0,10,20 ])
λ> zip a1 (a2 !> 1)
(Array D Seq (3)
  [ (0,3),(10,4),(20,5) ])
```

**Comment by kozross** [comment]
Not quite. Given the same ``a1,a2`` as you had in your entry

```haskell
> zipInner a1 a2
(Array D Seq (2 :. 3)
   [  [ (0,0), (1,10), (2,20)  ]
   ,  [ (3,0), (4,10), (5,20)  ]
   ])
```

Hopefully that makes more sense.

**Comment by lehins** [comment]
I see what you mean, but my guess is you mixed up values in tuples though, you expect it to work something like that:

```haskell
λ> a2 = makeArrayR D Seq (2 :. 3) (toLinearIndex (2 :. 3))
λ> a1 = makeArrayR U Seq (Ix1 3) (*10)
λ> zipInner a1 a2
(Array D Seq (2 :. 3)
  [ [ (0,0),(10,1),(20,2) ]
  , [ (0,3),(10,4),(20,5) ]
  ])
```
In that case you really do want the first array to be `Manifest` , cause you are indexing each element many times, and if you'd supply a delayed array each element would get computed as many times as your second array has rows. In example above `(*10)` operation would be executed 6 times, rather than 3 if compared with manifest array.

As far as second array goes, it's ok to have it delayed, but instead of just blindly using its size, we can compute intersecting size and use that for new array. If we do that we no longer need to check for bounds and we can safely use much faster `unsafeIndex` instead of `index'`. So I would write that `zipInner` like so:
```haskell

zipInner ::
     (Manifest r (Lower ix) a, Source r' ix b)
  => Array r (Lower ix) a
  -> Array r' ix b
  -> Array D ix (a, b)
zipInner a1 a2 = makeArray (getComp a1 <> getComp a2) sz go
  where
    go i = (unsafeIndex a1 (tailDim i), unsafeIndex a2 i)
    (k2, sz2lower) = unconsDim $ size a2
    sz = consDim k2 $ liftIndex2 min (size a1) sz2lower
```

Above function and `zipWith` et al. seem like could be useful. If you wanna follow this example and current zipping functions implementations in `Data.Massiv.Array.Ops.Map` and submit a PR, I'll be happy to merge it in.

**Comment by lehins** [comment]
Closing this for lack of interest. Feel free to reopen it if this functionality is still desired. I'll be happy to accept a PR with implementation, until then, I'll just mark it as won't fix.
