### ISSUE TITLE
Breaking changes in v0.4

### ISSUE THREAD

**Issue by jrp2014** [lehins/massiv#89]
I am having a go at updating https://github.com/masterdezign/10-days-of-grad/tree/master/day4 from 0.3 to 0.4 of massiv.

The main relevant massiv change seems to be that the pointwise matrix operators (.*, .+, .-, etc) are now .*., .-. etc, but with a different interface specification.  Ie, they are not just drop-in replacements.  If I have understood correctly , the operands need to be delayed, and the result is monadic (to catch incompatible operands, I assume).

Is there some documentation / examples for the v0.4 interface and how you envisage it being used?

Many thanks.

**Comment by lehins** [comment]
@jrp2014 Interface has changed to `MonadThrow` because pointwise operations are partial and sometimes we want to guard our computation against run time exceptions. For example a hypothetical function:

```haskell
mirrorMultiply :: 
  (Numeric r e, Source r Ix2 e) => Dim -> Array  r Ix2 e -> Maybe (Array  D Ix2 e)
mirrorMultiply dim arr = do
  arrMirror <- reverseM dim arr
  arrMirror .*. delay arr
```

As you suspected we do need to delay the original array `arr`. Using a monad we can chain many operations together that can fail, short circuiting on the first one that is invalid, without worrying about runtime exceptions (see I restricted monad to `Maybe` in example above)

That being said, if you want previous behavior of an error being thrown without worrying about all this monadic stuff you can simply delay the array and use it's `Num` instance. Above example translated to partial version:

```haskell
mirrorMultiply' :: Source r Ix2 e => Dim -> Array  r Ix2 e -> Array  D Ix2 e
mirrorMultiply' dim arr = reverse' dim arr * delay arr
```

FYI, in the future resort to massiv [channel on gitter](https://gitter.im/haskell-massiv/Lobby) for questions or stack overflow with `[massiv]` tag. Github issues are designated for bug reports and feature requests.

**Comment by jrp2014** [comment]
Thanks!
