### ISSUE TITLE
Has Massiv.sum changed behaviour?

### ISSUE THREAD

**Issue by ilCasinista** [lehins/massiv#97]
Hello again, I upgraded to massiv-0.5.2 (nightly-2020-05-10) and got some problems related to `Massiv.sum` (it used to work fine before). Here is the code:
```haskell
intToMat :: Int -> Massiv.Matrix Massiv.D Double -- For each integer a 5x5-Matrix
intToMat i = Massiv.makeArray Massiv.Seq (Massiv.Sz 5) (const (fromIntegral i))

vecOfMat :: Massiv.Vector Massiv.D (Massiv.Matrix Massiv.D Double) -- A 3-Vector of 5x5-Matrix.
vecOfMat = Massiv.makeArray Massiv.Seq (Massiv.Sz 3) intToMat

sumMat :: Massiv.Matrix Massiv.S Double -- This should be a 5x5-Matrix but it is 1x1-Matrix!
sumMat = Massiv.compute $ Massiv.sum vecOfMat

-- vecOfMat has size Massiv.Sz1 3 (its elements are arrays of size Massiv.Sz (5 :. 5))
-- sumMat should have size Massiv.Sz (5 :. 5) but it has size Massiv.Sz (1 :. 1)
```
Have I done something wrong? Thanks for your attention.

**Comment by lehins** [comment]
If I had to guess prior to the upgrade you where using `massiv < 0.4`, because that is the version where `Num` instance for `D` was changed. I guess it is a fault on my part for not being more explicit about it in the change log, all I did was adding this line to the change log, which probably doesn't mean much to an actual user:
> * Redefined most of the numeric operators with `Numeric`

In fact, I probably should have turned it into a runtime error instead of a silent semantic change, but it is already out there, so I won't dwell on it.

The behavior of `Num` instance prior to `massiv-0.4` was such that it treated singleton arrays specially. In other words a `1x1` matrix `A` added to `5x5` matrix `B` would give back a `5x5` matrix `C` which had the only element from `A` added to each of the elements of `B`. This was nice because it worked well with functions like `sum`, that relies on `fromIntegral`, which in turn is defined with `singleton`. Here is the transformation that happens behind the scenes: `sum = foldl (+) 0` => `sum = foldl (+) (fromIntegral 0)` => `sum = foldl (+) (singleton 0)`

Problem with such implementation is that for some mysterious to me reason it significantly affected the performance of all functions with arity 2 in `Num` instance (see #23), which forced me to change this behavior.

A possible workaround is to change `sumMat` function to:

```haskell
sumMat :: Matrix S Double -- This should be a 5x5-Matrix but it is 1x1-Matrix!
sumMat = compute $ getSum $ foldSemi Sum (Sum (makeArray Seq 5 (const 0))) vecOfMat
```

Alternative approach would be for you to not use array of arrays, but instead switch to a 3D array. This way you will have a guarantee that dimensions of all matrices you are trying to sum indeed have matching sizes.

Something along those lines:

```haskell
mat3D :: Int -> Array D Ix3 Double -- A 3-Vector of 5x5-Matrix.
mat3D i = makeArray Seq (Sz (3 :> 5 :. 5)) (const (fromIntegral i))

sumInner :: Array D Ix3 Double -> Matrix S Double
sumInner m = compute $ getSum $ foldSemi Sum zeroArr (fmap (m !>) (0 ..: p))
  where
    zeroArr = Sum (makeArray Seq (Sz2 r c) (const 0))
    Sz3 p r c = size m
```
Which gives you:
```haskell
λ> mat3D 5
Array D Seq (Sz (3 :> 5 :. 5))
  [ [ [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    ]
  , [ [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    ]
  , [ [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    , [ 5.0, 5.0, 5.0, 5.0, 5.0 ]
    ]
  ]
λ> sumInner $ mat3D 5
Array S Seq (Sz (5 :. 5))
  [ [ 15.0, 15.0, 15.0, 15.0, 15.0 ]
  , [ 15.0, 15.0, 15.0, 15.0, 15.0 ]
  , [ 15.0, 15.0, 15.0, 15.0, 15.0 ]
  , [ 15.0, 15.0, 15.0, 15.0, 15.0 ]
  , [ 15.0, 15.0, 15.0, 15.0, 15.0 ]
  ]
```

I think a proper solution for this would be to introduce a runtime error for binary function like `(+)` that would be triggered on mismatching array sizes. This way it would prevent surprising results like that. On more thing I think would be helpful is addition of a function `sumArrays`, that would do the right thing.

Thank you for bringing this up, it gives me some ideas what sort of functions would be helpful to add.

Notes for me to implement:

* [ ] Add to changelog for massiv-0.4.0 about changes in semantics of Num instance and other numeric functions.
* [ ] `foldInnerSliceSemi :: (InnerSlice r ix e, Semigroup m) => m -> (Elt r ix e -> m) -> Array r ix e -> m`
* [ ] `ifoldInnerSliceSemi :: (InnerSlice r ix e, Semigroup m) => m -> (Ix1 -> Elt r ix e -> m) -> Array r ix e -> m`
* [ ] Errors on mismatched sizes for binary operations
* [ ] `sumArrays :: (Source r ix e, Foldable f) => f (Array r ix e) -> Array D ix e`
* [ ] `productArrays :: (Source r ix e, Foldable f) => f (Array r ix e) -> Array D ix e`

**Comment by ilCasinista** [comment]
Thanks for the quick answer. I was puzzled because `+` for `D` works well. I didn't consider that `sum` uses not just `+` but also `0`. The correct `0` to be used should be the zero-matrix of the correct size. I just checked that both `0 + intToMat 1` and `intToMat 1 + 0` are of type `Array D Seq (Sz (1 :. 1))` instead of `Array D Seq (Sz (5 :. 5))`. Those new features will help. Maybe it's worth to point out this issue in the documentation of `(Index ix, Num e) => Num (Array D ix e)` in `Data.Massiv.Array.Delayed` and in the documentation of `sum` (use `sumArrays` for ...) and `product` (use `productArrays` for ...). Good job, thanks.

**Comment by ilCasinista** [comment]
Addendum: I'm not sure whether `sumArrays` (and `productArrays`) with those signatures can even be defined unless you use some type-dependency (e.g. like in package `vector-sized`).
For example, for `sumArrays` specialized for lists 
`sumArrays :: Source r ix e => [] (Array r ix e) -> Array D ix e`
what will it be `sumArrays [] :: Array D ix e` ?
The dimension will be determined (e.g. 1 for `Vector`) but what about the size?
For non-empty list `sum` could be implemented via some `fold1` (instead of `fold`) which uses `+` but not `0`.
That type-dependency (e.g. like in package `vector-sized`) would be a great feature (e.g. it would eliminate all the run-time size-mismatch errors) but it would involve a huge effort.

**Comment by lehins** [comment]
Sure you can. If you assume one of two modes:

* Fail on mismatch of sizes (what I suggest what `(+)` should do)
* Select minimum of the array sizes (which is what current `(+)` does)

```haskell
sumArrays :: Source r ix e => [Array r ix e] -> Array D ix e
sumArrays [] = empty
sumArrays (x:xs) = foldl (+) x xs
```

That is far from ideal, that is why I suggested to use 3D array, because it guarantee that sum of pages will be well behaved, because they are guaranteed to be of the same size.

`vector-sized` is a totally separate thing that will not work with massiv at all. It doesn't mean that technique used in `vector-sized` package cannot be used to wrap around massiv arrays, but I do not have enough bandwidth to work on it myself.

**Comment by ilCasinista** [comment]
Exactly, by using `fold1` (namely `foldl1`) I meant `sumArrays (x:xs) = foldl (+) x xs`. I'm not sure what would be best for `sumArrays []`; maybe let it fail instead of setting it to `empty` (the latter would rise something like `Array D Seq (Sz (0 :. 0))` and that might be confusing).
Sure using a 3D array would solve the problem here with that minimal example but I would have to do a lot of refactoring on the real code.
